### ISSUE TITLE
翻訳結果をDisplayAreaで表示

### ISSUE THREAD

**Issue by Spook-QuQ** [spook-QuQ/transplit-next#2]
- [x] ひとまず en → ja の翻訳結果を表示する
- [x] 言語切り替えのプルダウン作成

**Comment by spook-QuQ** [comment]
プルダウンじゃなくてスイッチ（ボタン）にした。
→ 今のところ「日本語・英語」間での翻訳しかないため。
→ 形態素解析のAPIが他の言語に対応していないため。（日本語と英語にのみ対応）

**Comment by Spook-QuQ** [comment]
プルダウンではなくスイッチボタン（入力と出力の言語を入れ替える）を実装した。
→ 今のところ「日本語・英語」間での翻訳しかないため。
→ 形態素解析のAPIが他の言語に対応していないため。（日本語と英語にのみ対応）
